version: '3.9'

services:
  app:
    container_name: classhero_frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  api:
    container_name: classhero_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev

  curator:
    container_name: classhero_curator
    build:
      context: ./content-curator
    ports:
      - "8000:8000"
    volumes:
      - ./content-curator:/app
    working_dir: /app
    env_file:
      - ./content-curator/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
